import { ApolloProvider } from "@/provider/ApolloProvider";
import "./globals.css";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Toadys Weather",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            {/* className={inter.className} */}
            <body>
                <ApolloProvider>{children}</ApolloProvider>
            </body>
        </html>
    );
}
